name: SketchyBar CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    name: Lint and Test SketchyBar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Find shell scripts
        id: find-scripts
        run: |
          echo "Found shell scripts in repository:"
          find . -type f \( -name "*.sh" -o -name "sketchybarrc" \) | tee scripts.txt
          echo "script-count=$(wc -l < scripts.txt)" >> $GITHUB_OUTPUT

      - name: Lint shell scripts with shellcheck
        run: |
          echo "🔍 Running shellcheck on shell scripts..."
          EXIT_CODE=0
          
          while IFS= read -r script; do
            echo "Checking: $script"
            if ! shellcheck -S error "$script"; then
              echo "❌ ShellCheck failed for: $script"
              EXIT_CODE=1
            else
              echo "✅ ShellCheck passed for: $script"
            fi
          done < scripts.txt
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "🎉 All shell scripts passed shellcheck!"
          else
            echo "⚠️ Some shell scripts failed shellcheck validation"
          fi
          
          exit $EXIT_CODE

      - name: Validate SketchyBar themes
        run: |
          echo "🎨 Running theme validation..."
          chmod +x themes/validate-themes.sh
          if ./themes/validate-themes.sh; then
            echo "✅ All themes are valid!"
          else
            echo "❌ Theme validation failed!"
            exit 1
          fi

      - name: Test theme manager functionality
        run: |
          echo "🧪 Running theme manager tests..."
          chmod +x tests/test-theme-manager.sh
          if ./tests/test-theme-manager.sh; then
            echo "✅ All theme manager tests passed!"
          else
            echo "❌ Theme manager tests failed!"
            exit 1
          fi

      - name: Lint Markdown files
        run: |
          echo "📝 Running markdownlint on markdown files..."
          if find . -name "*.md" -type f | grep -q .; then
            markdownlint **/*.md || {
              echo "❌ Markdown linting failed"
              exit 1
            }
            echo "✅ Markdown files passed linting!"
          else
            echo "ℹ️ No markdown files found to lint"
          fi

      - name: Check script permissions
        run: |
          echo "🔒 Checking script permissions..."
          
          while IFS= read -r script; do
            if [ ! -x "$script" ]; then
              echo "⚠️ Script not executable: $script"
              # Make it executable for better user experience
              chmod +x "$script"
              echo "   Fixed: Made $script executable"
            else
              echo "✅ Script is executable: $script"
            fi
          done < scripts.txt


      - name: Summary
        if: always()
        run: |
          echo "📊 SketchyBar CI Summary:"
          echo "- Scripts checked: $(cat scripts.txt | wc -l)"
          echo "- Themes available: $(find themes -name "*.sh" ! -name "validate-themes.sh" ! -name "template.sh" ! -name "theme-manager.sh" ! -name "load-theme.sh" | wc -l)"
          echo "- Markdown files: $(find . -name "*.md" | wc -l)"
          echo "- Plugins: $(find plugins -name "*.sh" 2>/dev/null | wc -l)"
          echo "- Items: $(find items -name "*.sh" 2>/dev/null | wc -l)"